server:
  # 应用启动端口
  port: 8090
  servlet:
    # 应用的访问路径
    context-path: /

spring:
  profiles:
    # 激活不同的配置文件
    active: druid
  # redis配置
  redis:
    # 超时时间
    connect-timeout: 10000ms
    # 服务器地址
    host: localhost
    # 端口号
    port: 6379
    # 数据库
    database: 2
    # 本地暂时没有配置密码
    password: 123456
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 1024
        # 最大等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

  # RabbitMQ配置
  rabbitmq:
    # 主机地址
    host: localhost
    # 用户名
    username: blog
    # 密码
    password: 123456
    # 虚拟主机
    virtual-host: /
    # 端口
    port: 5672
    listener:
      simple:
        # 消费者的最小数量
        concurrency: 10
        # 消费者的最大数量
        max-concurrency: 10
        # 限制消费者每次只能处理一条消息，处理完当前消息再处理下一条消息
        prefetch: 1
        # 启动时是否启动容器（默认为true）
        auto-startup: true
        # 当消息被拒绝时是否重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 开启重试
        enabled: true
        # 重试时间（默认1000ms）
        initial-interval: 1000
        # 重试次数（默认3次）
        max-attempts: 3
        # 重试最大间隔时间（默认10000ms）
        max-interval: 10000
        # 重试的间隔乘数：第一次等10s， 第二次等 10s * multiplier...
        multiplier: 1

  mail:
    # 邮件服务地址
    host: smtp.qq.com
    # 端口
    port: 465
    # 编码格式
    default-encoding: UTF-8
    # 用户名
    username: 1072876976@qq.com
    # 授权码
    password: hhxxnazqeyynbeif
    # 其它参数
    properties:
      mail:
        smtp:
          # 使用SSL方式
          ssl:
            enable: true
            required: true
        # 开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

# SpringBoot整合MybatisPlus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.zrkizzy.**.domain
  # 加载映射文件
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true
    # 开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl