server:
  # 应用启动端口
  port: 8090
  servlet:
    # 应用的访问路径
    context-path: /

spring:
  profiles:
    # 激活不同的配置文件
    active: druid
  # redis配置
  redis:
    # 超时时间
    connect-timeout: 10000ms
    # 服务器地址
    host: 49.234.13.224
    # 端口号
    port: 6379
    # 数据库
    database: 2
    # 本地暂时没有配置密码
    password: ZrkiZzy
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 1024
        # 最大等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

# SpringBoot整合MybatisPlus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.zrkizzy.**.domain
  # 加载映射文件
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true
    # 开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl